---
title: "Course lectures for Biol 417: Evolutionary Ecology"
output: html_document
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

__Essay Question__:

Pick any location on Earth. Describe the local conditions and how these will shape the evolution of organisms living in the location you have chosen.

 

_Points to consider_:

How do basic physical principles and the local geography interact to dictate the local environmental conditions?

How do the resulting environmental conditions, which resources are likely to be abundant, which resources are likely to be scarce, and the benefits/challenges that these conditions provide to living organisms?

 

__Useful Resources__:

- Pianka, E. R. (1999). Evolutionary ecology. Benjamin Cummings. Chapters 2-5. 

 

__Instructions:__

You are expected to write an essay addressing the above topic or question using the material covered in class, as well as additional sources from the scientific literature. The resources listed above are a useful place to start, but will not be sufficient. You can expect the material covered in the lectures will provide sufficient information for structuring the essay around the assigned topic but are also expected to expand beyond the material covered in the lectures.

 

__Submission__: Essays are to be submitted as word documents or PDFs (your choice) and uploaded to canvas before the due date. The essays should be a minimum of five pages in length (double spaced using a 12-point font). Include references to all necessary literature in a format of your choosing. References must be included, but do not count towards the total length.