---
title: "Course lectures for Biol 417: Evolutionary Ecology"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

__Essay Question__:

Pick any animal species. Describe the chosen species' social system and use the hypotheses covered in the lectures to provide an explanation for how their social system evolved.

 

_Hypotheses to cover_:

* __Predator Avoidance Hypothesis__: Aggregations serve to dilute the individual level predation threat.

* __Information Centre Hypothesis__: Aggregations provide individuals with information on the foraging activities of conspecifics.

* __Mate Guarding__: System specific. See lecture 26.

* __Resource Dispersion Hypothesis__: If the dispersion and renewal rate of local resources result in a territory that can viably accommodate multiple individuals, groups can arise without any specific benefits, assuming there are minimal costs to the 'primary territory holder'.

* __Safe Haven Hypothesis__: The relative costs and benefits of philopatry predict patterns in group-living.


__Instructions:__

You are expected to write an essay addressing the above topic or question using the material covered in class, as well as additional sources from the scientific literature. The resources listed above are a useful place to start, but will not be sufficient. You can expect the material covered in the lectures will provide sufficient information for structuring the essay around the assigned topic but are also expected to expand beyond the material covered in the lectures.

 

__Submission__: Essays are to be submitted as word documents or PDFs (your choice) and uploaded to canvas before the due date. The essays should be a minimum of five pages in length (double spaced using a 12-point font). Include references to all necessary literature in a format of your choosing. References must be included, but do not count towards the total length.