---
title: "Course lectures for Biol 417: Evolutionary Ecology"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Paper Summary 04

__Assigned paper__:

<!-- Peters, W., Hebblewhite, M., Mysterud, A., Eacker, D., Hewison, A. M., Linnell, J. D., ... & Cagnacci, F. (2019). Large herbivore migration plasticity along environmental gradients in Europe: life‐history traits modulate forage effects. Oikos, 128(3), 416-429. https://doi.org/10.1111/oik.05588 -->

Michelot, C., Leclerc, M., Taillon, J., Dussault, C., Hénault Richard, J., & Côté, S. D. (2023). Evidence of migratory coupling between grey wolves and migratory caribou. Oikos, e10150. https://doi.org/10.1111/oik.10150



__Instructions__:

The paper summaries should be no longer than one page (single spaced using a 12-point font). References should be included with the report but do not count towards the total length. The following points should be covered (not necessarily in the order given):

* What is/are the issue(s) addressed by the paper?
* What is the underlying research approach taken by the paper (e.g., a manipulative experiment, a correlational study, a theoretical model, a literature review, etc.)?
* What are the main results and what conclusions are expected to be drawn from the paper?
* How much confidence in the obtained results are implied by the author(s)?
* Is this confidence justified in your opinion?
     - were the authors scrupulous in discussing their results?
     - were there any weaknesses or limitations in the approach used by the authors?
     - can you think of an alternative interpretation not discussed by the authors?
 

__Submission__: It is expected that the assignment be submitted via Canvas as a word document or PDF (your choice). Paper summaries submitted by email will not be accepted unless agreed upon beforehand with the instructor.