---
title: "Course lectures for Biol 417: Evolutionary Ecology"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Paper Summary 03

__Assigned paper__:

<!-- Turbill, C., Bieber, C., & Ruf, T. (2011). Hibernation is associated with increased survival and the evolution of slow life histories among mammals. Proceedings of the Royal Society B: Biological Sciences, 278(1723), 3355-3363. https://doi.org/10.1098/rspb.2011.0190 -->

Winger, B. M., Auteri, G. G., Pegan, T. M., & Weeks, B. C. (2019). A long winter for the Red Queen: rethinking the evolution of seasonal migration. Biological Reviews, 94(3), 737-752. https://doi.org/10.1111/brv.12476

__Instructions__:

The paper summaries should be no longer than one page (single spaced using a 12-point font). References should be included with the report but do not count towards the total length. The following points should be covered (not necessarily in the order given):

* What is/are the issue(s) addressed by the paper?
* What is the underlying research approach taken by the paper (e.g., a manipulative experiment, a correlational study, a theoretical model, a literature review, etc.)?
* What are the main results and what conclusions are expected to be drawn from the paper?
* How much confidence in the obtained results are implied by the author(s)?
* Is this confidence justified in your opinion?
     - were the authors scrupulous in discussing their results?
     - were there any weaknesses or limitations in the approach used by the authors?
     - can you think of an alternative interpretation not discussed by the authors?
 

__Submission__: It is expected that the assignment be submitted via Canvas as a word document or PDF (your choice). Paper summaries submitted by email will not be accepted unless agreed upon beforehand with the instructor.